backend:
  name: github
  repo: gamer2810/prologue
  branch: master
  site_domain: beautiful-semolina-980a9f
  base_url: https://me.k3k.dev/
  

media_folder: "/assets/images"

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "_posts/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Layout", name: "layout", widget: "string", default: "post"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Comments", name: "comments", widget: "boolean", default: true}
      - {label: "Table of Contents", name: "toc", widget: "boolean", default: true}
      - {label: "Author", name: "author", widget: "string", default: "K3K"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "diary" # Used in routes, e.g., /admin/collections/blog
    label: "Diary Entry" # Used in the UI
    folder: "_diaryentry/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Layout", name: "layout", widget: "string", default: "post"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Author", name: "author", widget: "string", default: "K3K"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "reading-list" # Used in routes, e.g., /admin/collections/blog
    label: "Extra Reading" # Used in the UI
    folder: "_reading/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}
  